header:
  license:
    spdx-id: EPL-2.0
    copyright-owner: Contributors to the Eclipse Foundation
    content: |
      Copyright (c) 2022 Contributors to the Eclipse Foundation.

      This program and the accompanying materials are made
      available under the terms of the Eclipse Public License 2.0
      which is available at https://www.eclipse.org/legal/epl-2.0/
      SPDX-License-Identifier: EPL-2.0

      Contributors:

    pattern: |
      This program and the accompanying materials are made
      available under the terms of the Eclipse Public License 2.0
      which is available at https://www.eclipse.org/legal/epl-2.0/

  paths-ignore:
    - 'dist'
    - 'licenses'
    - '**/package-info.java'
    - '**/packageinfo'
    - '**/module-info.java'
    - '**/*.bnd'
    - '**/*.bndrun'
    - '**/*.xml'
    - '**/*.ecore'
    - '**/*.genmodel'
    - '**/*.md'
    - '**/*.MD'
    - '**/.keep'
    - '**/*.jetproperties'
    - '**/*.javajet'
    - '**/*.javajetinc'
    - '**/*.json'
    - '**/*.jsonld'
    - '**/*.csv'
    - '**/*.properties'
    - '**/*.maven'
    - '**/*.html'
    - '**/*.aird'
    - '**/*.basic'
    - '**/.classpath'
    - '**/.editorconfig'
    - 'LICENSE'
    - 'NOTICE'
    - 'DEPENDENCIES'
    - '.gitattributes'
    - '.github/**'
    - '.gitignore'
    - '.licenserc.yaml'
    - '.readthedocs.yaml'
    - '**/.project'
    - '**/*.prefs'
    - 'license.templates'
    - 'distribution/launcher/src/test/resources/repository/**'
    - 'distribution/launcher/src/test/resources/repository2/**'
    - 'docs/make.bat'
    - 'docs/Makefile'
    - 'docs/requirements.txt'
    - 'filters/esri.geometry/src/main/java/com/esri/core/geometry/SizeOf.java'
    - 'southbound/rules/easy-rules/osgi/src/main/resources/META-INF/license/easy-rules-license.txt'
    - 'southbound/sensorthings/sensing.rest/src/test/resources/NOTICE.txt'
    - 'southbound/sensorthings/sensing.rest/src/test/resources/frost-compose.yaml'
    - 'webclient/dist'
    - 'webclient/node_modules'
    - 'webclient/openapi'
    - 'webclient/.*'
    - 'webclient/scripts'
    - 'webclient/babel.config.js'
    - 'webclient/vue.config.js'

  comment: always
