# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

formats:
  - pdf
  - htmlzip

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

  apt_packages:
    - librsvg2-bin

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt
